feat: edit and delete urls
PraiseTy/shortit-ts pull request #6
Opened 2024-05-04 21:04 UTC by PraiseTy

2024-05-05 19:09 UTC, PraiseTy commented on .eslintrc.json
Commenting here because I don't think I'll push tonight. This rule was annoying me so I turned it off

2024-05-05 19:10 UTC, PraiseTy commented on src/routes/url.ts
will resolve this comment tomorrow

2024-05-06 22:44 UTC, greatertomi requested changes
Clean code. 😍 . Fix those minor issues and you're good to go.

I'm thinking, it would be neat if we can centralize the error handling instead of having try-catch on every controller. This is optional, but we could work on it together if you want.

2024-05-06 22:44 UTC, greatertomi commented on src/controllers/url.ts
> +        shortUrl: shortUrls || updateUrls.shortUrl,
```suggestion
        customName: updateUrls.customName,
        originalUrl: updateUrls.originalUrl,
        shortUrl: updateUrls.shortUrl,
```

2024-05-06 22:44 UTC, greatertomi commented on src/controllers/url.ts
> +    logger.error(`Error occured while deleting url: ${error}`);
```suggestion
    logger.error(`Error occurred while deleting url: ${error}`);
```

2024-05-06 22:47 UTC, PraiseTy commented
> Clean code. 😍 . Fix those minor issues and you're good to go.
> 
> I'm thinking, it would be neat if we can centralize the error handling instead of having try-catch on every controller. This is optional, but we could work on it together if you want.

I don't mind working on this, I could book a meeting for tomorrow?

2024-05-06 22:47 UTC, PraiseTy commented on src/controllers/url.ts
> +        shortUrl: shortUrls || updateUrls.shortUrl,
Alright, doing this now

2024-05-06 22:49 UTC, greatertomi commented
> I don't mind working on this, I could book a meeting for tomorrow?

That was a fast response. You can fix a meeting for tomorrow.

2024-05-06 22:52 UTC, PraiseTy commented
> > I don't mind working on this, I could book a meeting for tomorrow?
> 
> That was a fast response. You can fix a meeting for tomorrow.

Cool. I will. Also pushed the changes you requested

2024-05-06 23:34 UTC, greatertomi approved these changes

2024-05-07 00:28 UTC, merged